apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: marketplace-alert-rules
  namespace: openshift-marketplace
  labels:
    prometheus: alert-rules
    role: alert-rules
spec:
  groups:
    - name: marketplace.community_operators.rules
      rules:
        - record: app_registry:community_operators:1xx_response
          expr: sum(app_registry_request_total{code=~"1..",opsrc="community-operators"})
        - record: app_registry:community_operators:2xx_response
          expr: sum(app_registry_request_total{code=~"2..",opsrc="community-operators"})
        - record: app_registry:community_operators:3xx_response
          expr: sum(app_registry_request_total{code=~"3..",opsrc="community-operators"})
        - record: app_registry:community_operators:4xx_response
          expr: sum(app_registry_request_total{code=~"4..",opsrc="community-operators"})
        - record: app_registry:community_operators:5xx_response
          expr: sum(app_registry_request_total{code=~"5..",opsrc="community-operators"})
        - alert: CommunityOperatorConnectionErrors
          annotations:
            message: Unable to connect to the default OperatorSource community-operators AppRegistry for {{ $value }}% of requests.
          expr: rate(app_registry_request_total{code!~"2..",opsrc="community-operators"}[5m]) / rate(app_registry_request_total{opsrc="community-operators"}[5m]) >= 0.5
          for: 15m
          labels:
            severity: warning
    - name: marketplace.certified_operators.rules
      rules:
        - record: app_registry:certified_operators:1xx_response
          expr: sum(app_registry_request_total{code=~"1..",opsrc="certified-operators"})
        - record: app_registry:certified_operators:2xx_response
          expr: sum(app_registry_request_total{code=~"2..",opsrc="certified-operators"})
        - record: app_registry:certified_operators:3xx_response
          expr: sum(app_registry_request_total{code=~"3..",opsrc="certified-operators"})
        - record: app_registry:certified_operators:4xx_response
          expr: sum(app_registry_request_total{code=~"4..",opsrc="certified-operators"})
        - record: app_registry:certified_operators:5xx_response
          expr: sum(app_registry_request_total{code=~"5..",opsrc="certified-operators"})
        - alert: CertifiedOperatorConnectionErrors
          annotations:
            message: Unable to connect to the default OperatorSource certified-operators AppRegistry for {{ $value }}% of requests.
          expr: rate(app_registry_request_total{code!~"2..",opsrc="certified-operators"}[5m]) / rate(app_registry_request_total{opsrc="certified-operators"}[5m]) >= 0.5
          for: 15m
          labels:
            severity: warning
    - name: marketplace.redhat_operators.rules
      rules:
        - record: app_registry:redhat_operators:1xx_response
          expr: sum(app_registry_request_total{code=~"1..",opsrc="redhat-operators"})
        - record: app_registry:redhat_operators:2xx_response
          expr: sum(app_registry_request_total{code=~"2..",opsrc="redhat-operators"})
        - record: app_registry:redhat_operators:3xx_response
          expr: sum(app_registry_request_total{code=~"3..",opsrc="redhat-operators"})
        - record: app_registry:redhat_operators:4xx_response
          expr: sum(app_registry_request_total{code=~"4..",opsrc="redhat-operators"})
        - record: app_registry:redhat_operators:5xx_response
          expr: sum(app_registry_request_total{code=~"5..",opsrc="redhat-operators"})
        - alert: RedhatOperatorConnectionErrors
          annotations:
            message: Unable to connect to the default OperatorSource redhat-operators AppRegistry for {{ $value }}% of requests.
          expr: rate(app_registry_request_total{code!~"2..",opsrc="redhat-operators"}[5m]) / rate(app_registry_request_total{opsrc="redhat-operators"}[5m]) >= 0.5
          for: 15m
          labels:
            severity: warning
