apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: marketplace-operator
  namespace: openshift-marketplace
  labels:
    name: marketplace-operator
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - openshift-marketplace
  selector:
    matchLabels:
      name: marketplace-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-marketplace-metrics
  namespace: openshift-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-marketplace-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-marketplace-metrics
  namespace: openshift-marketplace
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
